### ISSUE TITLE
Contributing Python version

### ISSUE THREAD

**Issue by mad-man-moon** [tgmwri/csv2xle#1]
Hi, I'm very new to GitHub so I'm probably going about this the wrong way, but anyway. I wrote a csv2xle Python script that's a lot less elegant than yours, as I kind of just brute forced the file writing process (printing line by line instead of using xml libraries), mainly because I didn't see your script before writing mine. However, I'd like to contribute my script to this repo if possible, maybe as a starting point for a "proper" version. What would the best way to contribute this admittedly terrible code?
Thanks!

**Comment by strepon** [comment]
Hi, thanks for your interest, I was really surprised that someone found this script:)) Your Python version will be appreciated - I would suggest you to fork the repository, add your changes there and then create a pull request to this repository. (This is a common GitHub workflow, you can find tutorials about it if you are not familiar with that.)
